// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package products

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID          string
	StoreID     string
	Name        string
	Description pgtype.Text
	Price       pgtype.Numeric
	IsAvailable pgtype.Bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
