// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package products

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, store_id, name, description, price, is_available)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, store_id, name, description, price, is_available, created_at, updated_at
`

type CreateProductParams struct {
	ID          string
	StoreID     string
	Name        string
	Description pgtype.Text
	Price       pgtype.Numeric
	IsAvailable pgtype.Bool
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.StoreID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.IsAvailable,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
