// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        string
	Username  string
	Email     string
	Password  string
	RoleID    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
