// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package images

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (id, original_name, size, mime_type, path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, original_name, size, mime_type, path, created_at
`

type CreateImageParams struct {
	ID           string
	OriginalName string
	Size         int32
	MimeType     string
	Path         string
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.ID,
		arg.OriginalName,
		arg.Size,
		arg.MimeType,
		arg.Path,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.Size,
		&i.MimeType,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images
WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const getImage = `-- name: GetImage :one
SELECT id, original_name, size, mime_type, path, created_at
FROM images
WHERE id = $1
`

func (q *Queries) GetImage(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.Size,
		&i.MimeType,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}
