// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package images

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Image struct {
	ID           string
	OriginalName string
	Size         int32
	MimeType     string
	Path         string
	CreatedAt    pgtype.Timestamp
}
